name: seaworld
description: The official Aqua client app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# When updating this, make sure everything before the +
# matches everything before the + in assets/raw/version.txt.
# Here at Aqua, we use semver, so we can take advantage of
# pre-release, beta, alpha, and dev build indicators.
version: 0.0.0-dev+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mdi: ^5.0.0-nullsafety.0
  #get:
  graphql_flutter: ^5.0.0
  graphql: ^5.0.0
  gql_dio_link: ^0.1.0
  go_router: ^3.0.1
  flutter_riverpod: ^1.0.3
  dio: ^4.0.5-beta1
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  hive: ^2.0.4
  path_provider: ^2.0.2
  super_scaffold: ^0.0.4
  url_launcher: ^6.0.6
  mime_type: ^1.0.0
  # endless: ^1.6.0 # We will use this for chat.
  duration: ^3.0.8
  adaptive_breakpoints: ^0.1.1
  file_selector: ^0.8.2+1
  file_selector_windows:
  # probably have to add all the platforms for this bad boy

dev_dependencies:
  flutter_test:
    sdk: flutter

  # We're keeping this.
  flutter_lints: ^1.0.0

  # For test purposes...
  build_runner: ^2.1.1
  mockito: ^5.0.14
  hive_test: ^1.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/raw/version.txt 
    # Used to load version information
    # - assets/raw/notification.mp3
    # # Used as a default notification sound
    - assets/img/static.gif
    # Used as the background of the crash screen
    - assets/img/emptystate-normal.png
    # Used in empty states

    # == Translations ==
    - assets/lang/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
    - family: Public Sans
      fonts:
        - asset: assets/fonts/PublicSans-Regular.otf
          weight: 400
        - asset: assets/fonts/PublicSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/PublicSans-Medium.otf
          weight: 500
        - asset: assets/fonts/PublicSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/PublicSans-Bold.otf
          weight: 700
        - asset: assets/fonts/PublicSans-BoldItalic.otf
          weight: 700
          style: italic